"""Schema package for deposition simulation contracts."""

__version__ = "0.2.0"

from .sim_config import (
    AIBModelParamsSpec,
    AIBModelSpec,
    AIBOrdersSpec,
    ClassCompareSpec,
    CONFIG_ROOTS,
    DomainSpec,
    FluentInputSpec,
    FluentKeysSpec,
    InitScalarSpec,
    InitialConditionsSpec,
    InputsSpec,
    MeasurementSpec,
    OPT_CONFIG_ROOT,
    OptConfigV2,
    OptSpecV2,
    OrderEnumerationSpec,
    OutputSpec,
    ParameterFitSpec,
    ReferencePlaneSpec,
    RoleEnumerationSpec,
    RoleSpec,
    RunSpec,
    SIM_CONFIG_ROOT,
    SimConfigV2,
    SimSpecV2,
    TemperatureSpec,
    TimeSolverSpec,
    TimeSpec,
    compose_and_save_opt_config,
    compose_and_save_sim_config,
    compose_opt_config,
    compose_sim_config,
    register_sim_schema,
    resolve_config_root,
)

__all__ = [
    "__version__",
    "CONFIG_ROOTS",
    "SIM_CONFIG_ROOT",
    "OPT_CONFIG_ROOT",
    "FluentKeysSpec",
    "FluentInputSpec",
    "TemperatureSpec",
    "InputsSpec",
    "ReferencePlaneSpec",
    "DomainSpec",
    "RoleSpec",
    "AIBOrdersSpec",
    "AIBModelParamsSpec",
    "AIBModelSpec",
    "TimeSolverSpec",
    "TimeSpec",
    "InitScalarSpec",
    "InitialConditionsSpec",
    "MeasurementSpec",
    "OutputSpec",
    "SimSpecV2",
    "SimConfigV2",
    "ParameterFitSpec",
    "RoleEnumerationSpec",
    "OrderEnumerationSpec",
    "ClassCompareSpec",
    "OptSpecV2",
    "OptConfigV2",
    "RunSpec",
    "resolve_config_root",
    "register_sim_schema",
    "compose_sim_config",
    "compose_opt_config",
    "compose_and_save_sim_config",
    "compose_and_save_opt_config",
]
