# Auto-generated by scripts/preflight.sh
export ROOT_DIR="/Volumes/SP PX10/Main_code/CVD_ALD"
export PYTHON="/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
export PIP="/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip"
export MPLCONFIGDIR="/tmp"
export PYTHONPATH="/Volumes/SP PX10/Main_code/CVD_ALD/src"
