#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_SH="$ROOT_DIR/scripts/env.sh"

python_has_core_deps() {
  local exe="$1"
  "$exe" - <<'PY' >/dev/null 2>&1
import importlib.util
import sys

required = ("numpy", "hydra", "omegaconf", "matplotlib")
missing = [name for name in required if importlib.util.find_spec(name) is None]
raise SystemExit(0 if not missing else 1)
PY
}

collect_candidates() {
  local name="$1"
  type -a "$name" 2>/dev/null | sed -n "s/^${name} is //p"
}

create_wsl_python_shim() {
  if [[ ! -r /proc/version ]] || ! grep -qi microsoft /proc/version; then
    return
  fi
  if ! command -v py.exe >/dev/null 2>&1; then
    return
  fi
  if ! py.exe -3 -c "import numpy, hydra, omegaconf, matplotlib" >/dev/null 2>&1; then
    return
  fi

  local shim_dir="$ROOT_DIR/.wslbin"
  mkdir -p "$shim_dir"
  cat > "$shim_dir/python3" <<'SH'
#!/usr/bin/env bash
set -euo pipefail

launcher="$(command -v py.exe)"
translated=()
for arg in "$@"; do
  case "$arg" in
    /mnt/*)
      translated+=("$(wslpath -w "$arg")")
      ;;
    *=/mnt/*)
      key="${arg%%=*}"
      value="${arg#*=}"
      translated+=("$key=$(wslpath -w "$value")")
      ;;
    *)
      translated+=("$arg")
      ;;
  esac
done
exec "$launcher" -3 "${translated[@]}"
SH
  chmod +x "$shim_dir/python3"
}

choose_python() {
  local chosen=""
  local seen=""
  local -a py3_candidates=()
  local -a py_candidates=()

  if [[ -x "$ROOT_DIR/.venv/Scripts/python.exe" ]]; then
    py3_candidates+=("$ROOT_DIR/.venv/Scripts/python.exe")
  elif [[ -x "$ROOT_DIR/.venv/bin/python" ]]; then
    py3_candidates+=("$ROOT_DIR/.venv/bin/python")
  fi
  if [[ -x "$ROOT_DIR/.wslbin/python3" ]]; then
    py3_candidates+=("$ROOT_DIR/.wslbin/python3")
  fi
  if command -v python3 >/dev/null 2>&1; then
    py3_candidates+=("$(command -v python3)")
  fi
  if command -v python >/dev/null 2>&1; then
    py_candidates+=("$(command -v python)")
  fi

  while IFS= read -r path; do
    [[ -n "$path" ]] && py3_candidates+=("$path")
  done < <(collect_candidates python3)
  while IFS= read -r path; do
    [[ -n "$path" ]] && py_candidates+=("$path")
  done < <(collect_candidates python)

  for candidate in "${py3_candidates[@]}"; do
    [[ -x "$candidate" ]] || continue
    [[ ",$seen," == *",$candidate,"* ]] && continue
    seen="${seen},${candidate}"
    if python_has_core_deps "$candidate"; then
      chosen="$candidate"
      break
    fi
  done

  if [[ -z "$chosen" ]]; then
    for candidate in "${py_candidates[@]}"; do
      [[ -x "$candidate" ]] || continue
      [[ ",$seen," == *",$candidate,"* ]] && continue
      seen="${seen},${candidate}"
      if python_has_core_deps "$candidate"; then
        chosen="$candidate"
        break
      fi
    done
  fi

  if [[ -z "$chosen" ]]; then
    if command -v python3 >/dev/null 2>&1; then
      chosen="$(command -v python3)"
    elif command -v python >/dev/null 2>&1; then
      chosen="$(command -v python)"
    else
      echo "[preflight] ERROR: python3/python not found in PATH" >&2
      return 1
    fi
    echo "[preflight] WARNING: no python interpreter with {numpy,hydra,omegaconf,matplotlib} preinstalled was found in PATH order." >&2
  fi

  printf "%s\n" "$chosen"
}

create_wsl_python_shim
PYTHON="$(choose_python)"
echo "[preflight] Selected PYTHON=$PYTHON"

# Detect pip
PIP="$PYTHON -m pip"

# Default PYTHONPATH strategy
PYTHONPATH_EXPORT=""
if [[ -d "$ROOT_DIR/src" ]]; then
  # Keep existing PYTHONPATH if present, but append src.
  if [[ -n "${PYTHONPATH:-}" ]]; then
    PYTHONPATH_EXPORT="export PYTHONPATH=\"$ROOT_DIR/src:$PYTHONPATH\""
  else
    PYTHONPATH_EXPORT="export PYTHONPATH=\"$ROOT_DIR/src\""
  fi
fi

# Attempt editable install if pyproject.toml exists (non-fatal).
if [[ -f "$ROOT_DIR/pyproject.toml" ]]; then
  echo "[preflight] pyproject.toml detected. Attempting editable install (non-fatal)..."
  set +e
  eval "$PIP install -e . >/dev/null 2>&1"
  pip_code=$?
  set -e
  if [[ $pip_code -ne 0 ]]; then
    echo "[preflight] WARNING: pip install -e . failed (continuing with PYTHONPATH fallback)" >&2
  else
    echo "[preflight] Editable install OK."
  fi
else
  echo "[preflight] ERROR: pyproject.toml was not found at $ROOT_DIR." >&2
  exit 1
fi

# Write env.sh (Single Source of Truth for python/pip)
cat > "$ENV_SH" <<EOF
# Auto-generated by scripts/preflight.sh
export ROOT_DIR="$ROOT_DIR"
export PYTHON="$PYTHON"
export PIP="$PIP"
export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp}"
$PYTHONPATH_EXPORT
EOF

chmod +x "$ENV_SH"

echo "[preflight] Wrote $ENV_SH"
