#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# env.sh is generated by preflight.sh
if [[ -f "$ROOT_DIR/scripts/env.sh" ]]; then
  # shellcheck disable=SC1091
  source "$ROOT_DIR/scripts/env.sh"
else
  echo "[commands] ERROR: scripts/env.sh not found. Run ./scripts/preflight.sh first." >&2
  exit 1
fi

export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp}"

cmd_import_check() {
  "$PYTHON" -c "import deposim_schema, deposim_sim, deposim_report"
}

cmd_smoke() {
  "$PYTHON" -m deposim_sim.smoke
}

cmd_test() {
  "$PYTHON" -m unittest discover -s tests -p "test_*.py"
}

cmd_verify_p0() {
  cmd_import_check
  cmd_smoke
  cmd_test
}

cmd_show_env() {
  echo "ROOT_DIR=$ROOT_DIR"
  echo "PYTHON=$PYTHON"
  echo "PIP=$PIP"
  echo "PYTHONPATH=${PYTHONPATH:-}"
  echo "MPLCONFIGDIR=$MPLCONFIGDIR"
}

usage() {
  cat <<EOF
Usage: ./scripts/commands.sh <command>

Commands:
  show_env       Print resolved environment
  import_check   Import deposim_* packages
  smoke          Run minimal synthetic CVD steady simulation
  test           Run unit tests (stdlib unittest)
  verify_p0      import_check + smoke + test
EOF
}

case "${1:-}" in
  show_env) shift; cmd_show_env "$@";;
  import_check) shift; cmd_import_check "$@";;
  smoke) shift; cmd_smoke "$@";;
  test) shift; cmd_test "$@";;
  verify_p0) shift; cmd_verify_p0 "$@";;
  *) usage; exit 2;;
esac
