#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_SH="$ROOT_DIR/scripts/env.sh"

# Detect python
PYTHON="python3"
if command -v python3 >/dev/null 2>&1; then
  PYTHON="python3"
elif command -v python >/dev/null 2>&1; then
  PYTHON="python"
else
  echo "[preflight] ERROR: python3/python not found in PATH" >&2
  exit 1
fi

# Detect pip
PIP=""
if command -v pip3 >/dev/null 2>&1; then
  PIP="pip3"
elif command -v pip >/dev/null 2>&1; then
  PIP="pip"
else
  PIP="$PYTHON -m pip"
fi

# Default PYTHONPATH strategy
PYTHONPATH_EXPORT=""
if [[ -d "$ROOT_DIR/src" ]]; then
  # Keep existing PYTHONPATH if present, but append src.
  if [[ -n "${PYTHONPATH:-}" ]]; then
    PYTHONPATH_EXPORT="export PYTHONPATH=\"$ROOT_DIR/src:$PYTHONPATH\""
  else
    PYTHONPATH_EXPORT="export PYTHONPATH=\"$ROOT_DIR/src\""
  fi
fi

# Attempt editable install if pyproject.toml exists (non-fatal).
if [[ -f "$ROOT_DIR/pyproject.toml" ]]; then
  echo "[preflight] pyproject.toml detected. Attempting editable install (non-fatal)..."
  set +e
  eval "$PIP install -e . >/dev/null 2>&1"
  pip_code=$?
  set -e
  if [[ $pip_code -ne 0 ]]; then
    echo "[preflight] WARNING: pip install -e . failed (continuing with PYTHONPATH fallback)" >&2
  else
    echo "[preflight] Editable install OK."
  fi
else
  echo "[preflight] pyproject.toml not found yet (OK for initial autorun)."
fi

# Write env.sh (Single Source of Truth for python/pip)
cat > "$ENV_SH" <<EOF
# Auto-generated by scripts/preflight.sh
export ROOT_DIR="$ROOT_DIR"
export PYTHON="$PYTHON"
export PIP="$PIP"
export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp}"
$PYTHONPATH_EXPORT
EOF

chmod +x "$ENV_SH"

echo "[preflight] Wrote $ENV_SH"
